#!/bin/bash

# Start in root always
if [ ! -f .isroot ]
then
    echo "Must be run from root of project."; exit
fi
cd docker/

version=$(<../VERSION)

docker build  -t ntaylor22/pavlov-cpu:$version -t ntaylor22/pavlov-cpu:latest \
    --build-arg baseimage=ntaylor22/tensorflow-cpu \
    --build-arg reqfile=requirements.txt . &
docker build  -t ntaylor22/pavlov-cpu:latest-dev \
    --build-arg baseimage=ntaylor22/tensorflow-cpu \
    --build-arg reqfile=requirements-dev.txt . &
docker build  -t ntaylor22/pavlov-gpu:$version -t ntaylor22/pavlov-gpu:latest \
    --build-arg baseimage=ntaylor22/tensorflow-gpu \
    --build-arg reqfile=requirements.txt . &
docker build -t ntaylor22/pavlov-gpu:latest-dev \
    --build-arg baseimage=ntaylor22/tensorflow-gpu \
    --build-arg reqfile=requirements-dev.txt . &
wait
