#!/bin/bash

# Start in docker/ always
if [[ $(basename `pwd`) != docker ]]
then
    cd docker/
fi

read -p "Build GPU-enabled image? [Y/n] " gpu
if [[ $gpu =~ ^[Yy]$ ]]
then
    type=gpu
else
    type=cpu
fi

sed "s/base_image/ntaylor22\/tensorflow-$type/g" Dockerfile > Dockerfile2
docker build  -t gym-$type -f Dockerfile2 .

if [ ! -f jupyter_notebook_config.json ]
then
    script="from notebook.auth import passwd; c = passwd(); open('/home/pass_hash','w').write(c)"
    docker run --rm -it -v $PWD:/home gym-$type python3.6 -c "$script"
    echo "{\"NotebookApp\": {\"password\": \"`cat pass_hash`\"}}" > jupyter_notebook_config.json
fi
  
rm -f Dockerfile2 pass_hash
