#!/bin/bash

# Start in root always
if [ ! -f .isroot ]
then
    echo "Must be run from root of project."; exit
fi

if [ "$2" = "--no-cache" ]
then
    cache_opt='--no-cache'
else
    cache_opt=''
fi

version=$(<VERSION)

docker build  -t ntaylor22/pavlov-cpu:$version -t ntaylor22/pavlov-cpu:latest \
    --build-arg baseimage=ntaylor22/tensorflow-cpu \
    $cache_opt -f docker/Dockerfile .
docker build  -t ntaylor22/pavlov-gpu:$version -t ntaylor22/pavlov-gpu:latest \
    --build-arg baseimage=ntaylor22/tensorflow-gpu \
    $cache_opt -f docker/Dockerfile .
docker build  -t ntaylor22/pavlov-gpu:latest-dev \
    --build-arg baseimage=ntaylor22/tensorflow-gpu \
    $cache_opt -f docker/Dockerfile-dev .
docker build  -t ntaylor22/pavlov-cpu:latest-dev \
    --build-arg baseimage=ntaylor22/tensorflow-cpu \
    $cache_opt -f docker/Dockerfile-dev .
