ARG baseimage
FROM $baseimage

# gym requirements
RUN apt-get update && apt-get install -y zlib1g-dev libjpeg-dev xvfb \
                                         libav-tools xorg-dev python-opengl python3-tk \
                                         libboost-all-dev libsdl2-dev swig cmake

RUN pip install 'gym[all]'

COPY docker/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

CMD xvfb-run -s '-screen 0 1400x900x24' jupyter notebook --allow-root

RUN mkdir /root/.jupyter && \
    echo "c.NotebookApp.token = u''" > /root/.jupyter/jupyter_notebook_config.py

RUN rm -f /usr/bin/python && ln -s /usr/bin/python3.6 /usr/bin/python

COPY tests/ /tmp
