#!/bin/bash

# Start in root always
if [[ $(basename `pwd`) == docker ]]
then
    cd ../
fi

docker ps -a | grep gym -q
if [ $? -eq 0 ]; then
    docker rm -f gym
fi

port="8888"
while true;
do
    echo "Trying port = $port"
    netstat -ntpl 2> /dev/null | grep $port -q 
    if [ $? -eq 1 ]; then
        docker run --name gym -d -v $PWD:/home -v /tmp/.X11-unix:/tmp/.X11-unix \
                   -e DISPLAY=$DISPLAY -p $port:8888 -p 6006:6006 gym
        echo "Using port $port"
        break
    else
        ((port--))
    fi
done

if [ ! -f docker/jupyter_notebook_config.json ]; then
    docker exec -it gym bash -c 'jupyter notebook password --config /home/docker/jupyter_notebook_config.json'
fi
