#!/bin/bash

# Start in root always
if [ ! -f .isroot ]
then
    echo "Must be run from root of project."; exit
fi

docker rm -f gym 2> /dev/null

# will first try port 8888; if it's otherwise occupied, decrement until finding an open port
jup_port="8888"
tboard_port="6006"
while true;
do
    echo "Trying ports $jup_port and $tboard_port"
    netstat -ntpl 2> /dev/null | grep $jup_port -q 
    if [ $? -eq 1 ]; then
        netstat -ntpl 2> /dev/null | grep $tboard_port -q
        if [ $? -eq 1 ]; then
            if [[ $(docker images | grep 'pavlov-gpu') ]]
            then
                image=ntaylor22/pavlov-gpu
            else
                image=ntaylor22/pavlov-cpu
            fi
            docker run --name pavlov -d -v $PWD:/home -p $jup_port:8888 -p $tboard_port:6006 $image:latest
            echo "Using ports $jup_port and $tboard_port"
            break
        else
            ((tboard_port--))
        fi
    else
        ((jup_port--))
    fi
done
