#!/bin/bash

# Start in root always
if [ ! -f .isroot ]
then
    echo "Must be run from root of project."; exit
fi
cd docker/

docker rm -f gym

# will first try port 8888; if it's otherwise occupied, decrement until finding an open port
port="8888"
while true;
do
    echo "Trying port = $port"
    netstat -ntpl 2> /dev/null | grep $port -q 
    if [ $? -eq 1 ]; then
        if [[ $(docker images | grep 'gym-gpu') ]]
        then
            image=gym-gpu
        else
            image=gym-cpu
        fi
        docker run --name gym -d -v $PWD:/home -v /tmp/.X11-unix:/tmp/.X11-unix \
                   -e DISPLAY=$DISPLAY -p $port:8888 -p 6006:6006 $image
        echo "Using port $port"
        break
    else
        ((port--))
    fi
done
